steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/my-rust-app:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/${_PROJECT_ID}/my-rust-app:latest'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create a new release in the delivery pipeline
        gcloud deploy releases create release-$(date +%Y%m%d%H%M%S) \
          --delivery-pipeline=${_PIPELINE_NAME} \
          --region=${_DEFAULT_REGION} \
          --images=climb_service=gcr.io/${_DEFAULT_REGION}/my-rust-app:latest \

images:
  - 'gcr.io/${_PROJECT_ID}/my-rust-app:latest'
