steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/my-rust-app:latest'
      - '--build-arg'
      - '_PROJECT_ID=${_PROJECT_ID}'
      - '--build-arg'
      - '_DEFAULT_REGION=${_DEFAULT_REGION}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/${_PROJECT_ID}/my-rust-app:latest'

  # run unit tests
  - name: 'rust:latest'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      cargo test

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create a new release in the delivery pipeline
        gcloud deploy releases create release-$(date +%Y%m%d%H%M%S) \
          --delivery-pipeline=${_PIPELINE_NAME} \
          --region=${_DEFAULT_REGION} \
          --images=climb_service=gcr.io/${_PROJECT_ID}/my-rust-app:latest \

images:
  - 'gcr.io/${_PROJECT_ID}/my-rust-app:latest'
