steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/climbing-app-424905/my-rust-app:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/climbing-app-424905/my-rust-app:latest'

images:
  - 'gcr.io/climbing-app-424905/my-rust-app:latest'
