steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/my-rust-app:latest'
      - '--build-arg'
      - '_PROJECT_ID=${_PROJECT_ID}'
      - '--build-arg'
      - '_DEFAULT_REGION=${_DEFAULT_REGION}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/${_PROJECT_ID}/my-rust-app:latest'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Deploy directly to Google Cloud Run
        gcloud run deploy integ-cloud-run \
          --image=gcr.io/${_PROJECT_ID}/my-rust-app:latest \
          --region=${_DEFAULT_REGION} \
          --platform=managed \
          --no-allow-unauthenticated \
          --add-cloudsql-instances=climbing-app-426701:us-central1:beta-postgres-instance \
          --set-env-vars=DB_USER=postgres,DB_PASSWORD=postgres,DB_NAME=postgres,SQL_CONNECTION_NAME=/cloudsql/climbing-app-426701:us-central1:beta-postgres-instance

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e # Exit immediately if a command exits with a non-zero status
        SERVICE_URL=$(gcloud run services describe integ-cloud-run --region us-central1 --format 'value(status.url)')
        ID_TOKEN=$(gcloud auth print-identity-token --impersonate-service-account=528022003338@cloudbuild.gserviceaccount.com)
        cargo test

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create a new release in the delivery pipeline
        gcloud deploy releases create release-$(date +%Y%m%d%H%M%S) \
          --delivery-pipeline=${_PIPELINE_NAME} \
          --region=${_DEFAULT_REGION} \
          --images=climb_service=gcr.io/${_PROJECT_ID}/my-rust-app:latest \

images:
  - 'gcr.io/${_PROJECT_ID}/my-rust-app:latest'
