apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: climb-service
build:
  local:
    push: true

  platforms: ["linux/amd64"]

  artifacts:
  - image: gcr.io/climbing-app-424905/climb_service
    docker:
      dockerfile: ./Dockerfile

manifests:
  rawYaml:
    - resources/service.yaml

deploy:
  cloudrun:
    region: us-south1
    projectid: climbing-app-424905
