apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: climb-service
build:
  artifacts:
  - image: gcr.io/climbing-app-424905/climb_service
deploy:
  googleCloudDeploy:
    deliveryPipeline: climb-service-pipeline
    region: us-south1
    targets:
      - targetId: beta
        run:
          location: us-south1
          service: climb-service
