apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: climb-service
build:
  artifacts:
  - image: gcr.io/climbing-app-424905/climb_service
deploy:
  cloudrun:
    region: us-south1
    project: climbing-app-424905
    service: climb-service
