apiVersion: skaffold/v4beta9
kind: Config

build:
  local:
    push: true

  platforms: ["linux/amd64"] # <- Specific platform supported by Cloud Run

  artifacts:
    - image: gcr.io/$_PROJECT_ID/my-rust-app
      docker:
        buildArgs:
          _PROJECT_ID: $_PROJECT_ID
        dockerfile: ./Dockerfile2

manifests:
  rawYaml:
    - resources/service.yaml

deploy:
  cloudrun:
    projectid: $_PROJECT_ID
    region: $_DEFAULT_REGION
