apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: beta-cloud-run
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: 'climbing-app-426701:us-central1:beta-postgres-instance' 
    spec:
      containers:
      - image: gcr.io/climbing-app-426701/my-rust-app
        env:
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: postgres
          - name: DB_NAME
            value: postgres
          - name: SQL_CONNECTION_NAME
            value: /cloudsql/climbing-app-426701:us-central1:beta-postgres-instance
